### ISSUE TITLE
MQ RPC Client

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-mq-cpp#1]
As a blockchain engineer, I would like a way to make remote procedure calls over the MQ server.

- [x] Create a class with an interface that allows for RPC calls to be made that return futures (#2)
- [x] Create a threadsafe data structure of your choice to maintain outstanding requests (#3)
- [x] Implement a separate read thread to resolve or timeout promises (#4)

**Note:** Look in `net` for design inspiration
